export const HTTP_STATUSES = [
  { name: "2xx Success", statuses: [
    { code: 200, label: "OK" },
    { code: 201, label: "Created" },
    { code: 202, label: "Accepted" },
    { code: 203, label: "Non-Authoritative Information" },
    { code: 204, label: "No Content" },
    { code: 205, label: "Reset Content" },
    { code: 206, label: "Partial Content" },
    { code: 207, label: "Multi-Status" },
    { code: 208, label: "Already Reported" },
    { code: 226, label: "IM Used" },
  ]},
  { name: "3xx Redirection", statuses: [
    { code: 300, label: "Multiple Choices" },
    { code: 301, label: "Moved Permanently" },
    { code: 302, label: "Found" },
    { code: 303, label: "See Other" },
    { code: 304, label: "Not Modified" },
    { code: 307, label: "Temporary Redirect" },
    { code: 308, label: "Permanent Redirect" },
  ]},
  { name: "4xx Client Errors", statuses: [
    { code: 400, label: "Bad Request" },
    { code: 401, label: "Unauthorized" },
    { code: 402, label: "Payment Required" },
    { code: 403, label: "Forbidden" },
    { code: 404, label: "Not Found" },
    { code: 405, label: "Method Not Allowed" },
    { code: 406, label: "Not Acceptable" },
    { code: 407, label: "Proxy Authentication Required" },
    { code: 408, label: "Request Timeout" },
    { code: 409, label: "Conflict" },
    { code: 410, label: "Gone" },
    { code: 411, label: "Length Required" },
    { code: 412, label: "Precondition Failed" },
    { code: 413, label: "Content Too Large" },
    { code: 414, label: "URI Too Long" },
    { code: 415, label: "Unsupported Media Type" },
    { code: 416, label: "Range Not Satisfiable" },
    { code: 417, label: "Expectation Failed" },
    { code: 418, label: "I'm a Teapot" },
    { code: 421, label: "Misdirected Request" },
    { code: 422, label: "Unprocessable Content" },
    { code: 423, label: "Locked" },
    { code: 424, label: "Failed Dependency" },
    { code: 425, label: "Too Early" },
    { code: 426, label: "Upgrade Required" },
    { code: 428, label: "Precondition Required" },
    { code: 429, label: "Too Many Requests" },
    { code: 431, label: "Request Header Fields Too Large" },
    { code: 451, label: "Unavailable For Legal Reasons" },
  ]},
  { name: "5xx Server Errors", statuses: [
    { code: 500, label: "Internal Server Error" },
    { code: 501, label: "Not Implemented" },
    { code: 502, label: "Bad Gateway" },
    { code: 503, label: "Service Unavailable" },
    { code: 504, label: "Gateway Timeout" },
    { code: 505, label: "HTTP Version Not Supported" },
    { code: 506, label: "Variant Also Negotiates" },
    { code: 507, label: "Insufficient Storage" },
    { code: 508, label: "Loop Detected" },
    { code: 510, label: "Not Extended" },
    { code: 511, label: "Network Authentication Required" },
  ]},
]